// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOMQMbFvby8F0mYREA9yw4-K_zLguk61w',
    appId: '1:828528303456:web:6da38a9554c9b0c8739205',
    messagingSenderId: '828528303456',
    projectId: 'fitquest-39933',
    authDomain: 'fitquest-39933.firebaseapp.com',
    storageBucket: 'fitquest-39933.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgpaeraOiVT3imnu1xRXrB-wvGPsidrQY',
    appId: '1:828528303456:android:99e770c1651fd00e739205',
    messagingSenderId: '828528303456',
    projectId: 'fitquest-39933',
    storageBucket: 'fitquest-39933.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvhN-loJDDIoJ9HjQEA0q44c4Ud18KrRQ',
    appId: '1:828528303456:ios:ff1451f1e1d79cd5739205',
    messagingSenderId: '828528303456',
    projectId: 'fitquest-39933',
    storageBucket: 'fitquest-39933.firebasestorage.app',
    iosBundleId: 'com.example.fitQuest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvhN-loJDDIoJ9HjQEA0q44c4Ud18KrRQ',
    appId: '1:828528303456:ios:ff1451f1e1d79cd5739205',
    messagingSenderId: '828528303456',
    projectId: 'fitquest-39933',
    storageBucket: 'fitquest-39933.firebasestorage.app',
    iosBundleId: 'com.example.fitQuest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOMQMbFvby8F0mYREA9yw4-K_zLguk61w',
    appId: '1:828528303456:web:1c5c1d0328f84f2f739205',
    messagingSenderId: '828528303456',
    projectId: 'fitquest-39933',
    authDomain: 'fitquest-39933.firebaseapp.com',
    storageBucket: 'fitquest-39933.firebasestorage.app',
  );
}
